### ISSUE TITLE
Issue showing view

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [jackpocket/android_scratchoff#1]
I have add this view above edittext view but when i scatch all now cant write on edittext so any solution for this so after scatch full we can write to on below view (Edittext)

**Comment by mattsilber** [comment]
I haven't tried this, but you could probably just set the visibility of the ScratchableLayout  (or whatever your scratch View is) when the finish callback is triggered:

    .setCompletionCallback(() -> 
        View.postDelayed (() -> view.setVisibility(View.GONE), 300));

Where 'view' is your ScratchableLayout.

I did postDelayed there so that the clearing animation has time to run before hiding it.

**Comment by zuiaisha1** [comment]
how to reset the view? i try to use ScratchoffController 's reset method ,but the result is bad

**Comment by mattsilber** [comment]
Sorry, good catch. In it's current state, `ScratchController.reset()` should have been an internal private method on the controller as `ScratchoffController.attach(View, View)` needs to rebuild the `ScratchLayoutDrawer` in order to reset the scratchable View to an untouched state.

For now, calling `attach(View, View)` or creating a new `ScratchController` and attaching that will solve your problem. In the next revision, I'll fix that to expose the `reset()` functionality correctly.

**Comment by yemamumu** [comment]
I can't see log when i scratch above 90%；
This is my code：
mScratcCcontroller = new ScratchoffController(this)
                .setThresholdPercent(0.50d)
                .setTouchRadiusDip(this, 30)
                .setFadeOnClear(true)
                .setClearOnThresholdReached(true)
                .setCompletionCallback(new Runnable() {
                    @Override
                    public void run() {
                        LogUtil.e("----setCompletionCallback--");
                    }
                })
                .attach(findViewById(R.id.scratchView), findViewById(R.id.llDiscNoteContent));

**Comment by mattsilber** [comment]
@yemamumu you have the threshold set to 50%, which would trigger the clear event after only 50% of the View has been scratched away. You should call `.setThresholdPercent(0.90d)` if you want it to clear after 90%. 

Note: Keep in mind, 90% of the View can be a pretty large area for the user to scratch; especially with larger Views.

**Comment by yemamumu** [comment]
thanks,  can you give me a demo?  
My email : yema@lljz-inc.com

**Comment by dovahkrid** [comment]
I want to set the scratch image and reset the controller to "scratch" again. I tried to reset and attach (even reset and call a new controller). But the view just seems to disappear.
`if(controller != null) {
            scratch_img.setImageBitmap(bmap);
            controller.reset();
            controller.attach(scratchView, frame_layout);
        }
        else{
            scratch_img.setImageBitmap(bmap);
            controller = new ScratchoffController(StickerActivity.this)
                    .attach(scratchView, frame_layout);
        }`

**Comment by mattsilber** [comment]
That exception is handled so you shouldn't need to worry (albeit it probably would have been better practice to have checked for it), but the issue you're experiencing is definitely strange, and I'm wondering if it might have something to do with setting the Bitmap.

Since I still haven't [updated the reset() method](https://github.com/jackpocket/android_scratchoff/issues/1#issuecomment-241760372), it probably won't work as expected... For the moment, just create and attach the controller each time and it should work correctly.

**Comment by dovahkrid** [comment]
Not working

```
if(controller == null) { //call the first time
            scratch_img.setImageBitmap(bmap);
            controller = new ScratchoffController(context).attach(scratchView, frame_layout);
        }
        else{ //reset if it already has controller
            controller = null;
            scratch_img.setImageBitmap(bmap);
            controller = new ScratchoffController(context).attach(scratchView, frame_layout);
        }
```

**Comment by mattsilber** [comment]
Try this now, it should be fixed:

```
scratch_img.setImageBitmap(bmap);

if(controller == null)
    controller = new ScratchoffController(context)
            .attach(scratchView, frame_layout);
else
    controller.reset();
```
