### ISSUE TITLE
Scratch Percentage

### ISSUE THREAD

**Issue by burakkoray** [jackpocket/android_scratchoff#3]
Hi
Thanks for the great project ?
Is there any way to get scratch percentage ?

**Comment by mattsilber** [comment]
Unfortunately, I didn't see a need for knowing the percentage when I wrote the [ThresholdProcessor](https://github.com/jackpocket/android_scratchoff/blob/master/src/main/java/com/jackpocket/scratchoff/processors/ThresholdProcessor.java), so the actual value isn't exposed directly at this time. (My bad)

I'm not quite sure if I'm going to get the chance to expose that anytime soon, but if you want to fork it in the meantime, you should be able to adjust `processImage()` in the file I linked. The `double percentScratched` on the first line would be the percentage scratched on the current pass. You would then need to store that value at the class-level, and then expose the `ThresholdProcessor` from inside the `ScratchController` so that you can access it from your implementation.
